fix detect breaking ci

diff --git a/.github/workflows/labels.yml b/.github/workflows/labels.yml
--- a/.github/workflows/labels.yml
+++ b/.github/workflows/labels.yml
@@ -24,24 +24,36 @@ jobs:
   # we can expand to all cases after
   apply-breaking:
     runs-on: ubuntu-latest
-    if: ${{ github.event.action == 'opened' && github.actor != 'dependabot[bot]' }}
+    if: |
+      (github.event.action == 'opened' || 
+      github.event.action == 'synchronize' || 
+      github.event.action == 'reopened') &&
+      github.actor != 'dependabot[bot]'
     permissions:
       pull-requests: write
+      contents: read
 
     steps:
       - uses: actions/checkout@v4
         with:
           fetch-depth: 0
 
+      - name: Fetch and check out base branch
+        run: |
+          git fetch origin ${{ github.event.pull_request.base.ref }}
+          git checkout ${{ github.event.pull_request.base.ref }}
+
       - name: Run check for breaking
         id: breaking_change
         run: |
-          git fetch origin main
+          git merge --no-commit --no-ff ${{ github.sha }}
           make detect-breaking
+        continue-on-error: true  # Continue even if this step fails, so we can still label the PR
 
       - name: Add label if breaking changes detected
         if: failure()
-        run: gh issue edit "$NUMBER" --add-label "$LABELS"
+        run: |
+          gh issue edit "$NUMBER" --add-label "$LABELS" || echo "Label already exists or failed to apply label."
         env:
           GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
           GH_REPO: ${{ github.repository }}
